 @api = http://localhost:3000/productos

### Todos los productos
GET {{ api }}

### Crear producto
POST {{ api }}
Content-type: application/json

{
    "sapcode": 99,
    "name": "Producto Nuevo",
    "presentation": "GARDEN HOUSE GARCINOL MAX COM X301",
    "laboratorio": "GARDEN HOUSE1",
    "droga": "GARCINIA CAMBOGIA+ASOC.2",
    "salta": 3,
    "chaco": 4,
    "precio": 323.87
}

### Detalle de producto
GET {{ api }}/73062

### Borrar un producto
DELETE {{ api }}/21999


### Actualizar un producto
PUT {{ api }}/899999
Content-type: application/json

{
    "name": "Producto Actualizado",
    "presentation": "General mix",
    "laboratorio": "GARDEN HOUSE1",
    "droga": "GARCINIA CAMBOGIA+ASOC.2",
    "tucuman": 8,
    "salta": 3,
    "chaco": 4,
    "precio": 300.87
}

### Obtener total de Productos
GET {{ api }}/total

### Obtener total de Productos por Laboratorio
GET {{ api }}/productos-por-laboratorio